# ruff: noqa: F403, F405, E501
from .generate_base import *  # noqa: F403

# fmt: off
from .generate_p1 import _collect_params, _dedup_suffix, _infer_command_name, _slugify, _tag_to_group, _tag_to_module  # noqa: E402,E501
from .generate_p2 import _generate_command_func  # noqa: E402,E501
# fmt: on


def _generate_module(tag: str, operations: list[tuple[str, str, dict]]) -> str:
    """Generate a complete Python module for a given tag."""
    module_name = _tag_to_module(tag)
    group_name = _tag_to_group(tag)
    group_var = f"{module_name}_group"

    group_decorator = f'@click.group("{group_name}")'
    group_signature = f"def {group_var}(ctx):"
    if tag.lower() == "ping":
        group_decorator = f'@click.group("{group_name}", invoke_without_command=True)'
    group_lines = [
        f'    """{_slugify(tag)} resource commands."""',
    ]
    if tag.lower() == "ping":
        group_lines.extend(
            [
                "    if ctx.invoked_subcommand is None:",
                "        ctx.invoke(_cmd_list_)",
            ]
        )

    header_lines = [
        f'"""Commands for the Mailchimp /{group_name} API resource.',
        "",
        "Auto-generated by cli_anything/mailchimp/_codegen/generate.py.",
        "Do not edit manually — re-run the generator to update.",
        '"""',
        "",
        "import json",
        "",
        "import click",
        "",
        "",
        "def _parse_json_option(value, option_name, require_object=False):",
        "    try:",
        "        parsed = json.loads(value)",
        "    except json.JSONDecodeError as exc:",
        "        raise click.BadParameter(",
        '            f"must be valid JSON ({exc.msg})",',
        "            param_hint=option_name,",
        "        ) from exc",
        "    if require_object and not isinstance(parsed, dict):",
        '        raise click.BadParameter("must be a JSON object", param_hint=option_name)',
        "    return parsed",
        "",
        "",
        group_decorator,
        "@click.pass_context",
        group_signature,
        *group_lines,
        "",
        "",
    ]
    header = "\n".join(header_lines)

    body_parts: list[str] = []
    # Track ALL assigned names (base + deduped) to guarantee uniqueness.
    assigned: set[str] = set()

    for method, path, operation in sorted(operations, key=lambda x: (x[1], x[0])):
        op_id = operation.get("operationId", "")
        cmd_name = _infer_command_name(method, path, op_id)

        # I4: De-duplicate using operationId slug; fall back to counter if still collides.
        if cmd_name in assigned:
            candidate = _dedup_suffix(cmd_name, path, op_id, 2)
            counter = 2
            while candidate in assigned:
                counter += 1
                candidate = f"{cmd_name}-{counter}"
            cmd_name = candidate

        assigned.add(cmd_name)

        operation = dict(operation)
        operation.setdefault("tags", [tag])

        path_params, query_params, body_param = _collect_params(operation, path)
        func_code = _generate_command_func(
            cmd_name, method, path, operation, path_params, query_params, body_param
        )
        body_parts.append(func_code)
        if tag.lower() == "campaigns" and cmd_name == "list-campaigns-id-content":
            body_parts.append(
                'campaigns_group.add_command(_cmd_list_campaigns_id_content, "list-content")\n'
            )
        if (
            tag.lower() == "campaigns"
            and cmd_name == "list-campaigns-id-send-checklist"
        ):
            body_parts.append(
                'campaigns_group.add_command(_cmd_list_campaigns_id_send_checklist, "list-send-checklist")\n'
            )
        if tag.lower() == "reports" and cmd_name == "list-reports-id-click-details":
            body_parts.append(
                'reports_group.add_command(_cmd_list_reports_id_click_details, "list-click-details")\n'
            )
        if (
            tag.lower() == "reports"
            and cmd_name == "list-reports-id-domain-performance"
        ):
            body_parts.append(
                'reports_group.add_command(_cmd_list_reports_id_domain_performance, "list-domain-performance")\n'
            )
        if tag.lower() == "reports" and cmd_name == "list-reports-id-email-activity":
            body_parts.append(
                'reports_group.add_command(_cmd_list_reports_id_email_activity, "list-email-activity")\n'
            )
        if tag.lower() == "reports" and cmd_name == "list-reports-id-locations":
            body_parts.append(
                'reports_group.add_command(_cmd_list_reports_id_locations, "list-locations")\n'
            )
        if tag.lower() == "reports" and cmd_name == "list-reports-id-open-details":
            body_parts.append(
                'reports_group.add_command(_cmd_list_reports_id_open_details, "list-open-details")\n'
            )
        if tag.lower() == "reports" and cmd_name == "list-reports-id-unsubscribed":
            body_parts.append(
                'reports_group.add_command(_cmd_list_reports_id_unsubscribed, "list-unsubscribed")\n'
            )
        if tag.lower() == "automations" and cmd_name == "list-automations-id-emails":
            body_parts.append(
                'automations_group.add_command(_cmd_list_automations_id_emails, "list-emails")\n'
            )
        if tag.lower() == "lists" and cmd_name == "create-lists-id-members":
            body_parts.append(
                'lists_group.add_command(_cmd_create_lists_id_members, "create-members")\n'
            )
        if tag.lower() == "lists" and cmd_name == "list-preview-a-segment":
            body_parts.append(
                'lists_group.add_command(_cmd_list_preview_a_segment, "list-lists-id-segments")\n'
            )

    return header + "\n".join(body_parts)


def load_spec(url: str = SPEC_URL) -> dict:
    print(f"Fetching spec from {url} ...", file=sys.stderr)
    resp = requests.get(url, timeout=60)
    resp.raise_for_status()
    return resp.json()
