# ruff: noqa: E501
"""Commands for the Mailchimp /landing-pages API resource.

Auto-generated by cli_anything/mailchimp/_codegen/generate.py.
Do not edit manually — re-run the generator to update.
"""

import json

import click

__all__ = ["click", "json"]
