# ruff: noqa: F403, F405, E501
from .freecad_live_preview_demo_base import *  # noqa: F403


def __curiosity_steps_lg0_8():
    return [
        {
            "id": "align-right-rear-axle-block",
            "label": "Attach right rear axle block",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "23",
                "17",
                "--x",
                "center",
                "--to-x",
                "center",
                "--y",
                "max",
                "--to-y",
                "min",
                "--z",
                "max",
                "--to-z",
                "max",
                "--dz",
                "1.0",
            ],
            "wait_preview": True,
        },
        {
            "id": "left-rocker-pivot-housing",
            "label": "Add left rocker pivot housing",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "LeftRockerPivotHousing",
                "-P",
                "length=8",
                "-P",
                "width=8",
                "-P",
                "height=6",
                "-pos",
                "11,-22,21",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-left-rocker-pivot-housing",
            "label": "Seat left rocker pivot housing",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "24",
                "4",
                "--x",
                "center",
                "--to-x",
                "center",
                "--y",
                "min",
                "--to-y",
                "min",
                "--z",
                "max",
                "--to-z",
                "max",
                "--dz",
                "3.0",
            ],
            "wait_preview": True,
        },
        {
            "id": "right-rocker-pivot-housing",
            "label": "Add right rocker pivot housing",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "RightRockerPivotHousing",
                "-P",
                "length=8",
                "-P",
                "width=8",
                "-P",
                "height=6",
                "-pos",
                "11,17,21",
            ],
            "wait_preview": True,
        },
    ]
