# ruff: noqa: F403, F405, E501
from .freecad_live_preview_demo_base import *  # noqa: F403


def _mod_cg2_0():
    return [
        {
                "id": "create-project",
                "label": "Create FreeCAD project",
                "argv": ["document", "new", "--name", "EmpireStateBuilding", "-o", "{project_path}"],
                "wait_preview": False,
            },
        {
                "id": "start-live-preview",
                "label": "Start poll-mode live preview",
                "argv": [
                    "-p",
                    "{project_path}",
                    "preview",
                    "live",
                    "start",
                    "--recipe",
                    "quick",
                    "--mode",
                    "poll",
                    "--source-poll-ms",
                    "500",
                    "--poll-ms",
                    "700",
                    "--root-dir",
                    "{live_root}",
                ],
                "wait_preview": True,
                "manual_session_payload": True,
            },
        {
                "id": "podium",
                "label": "Add podium base",
                "argv": [
                    "-p",
                    "{project_path}",
                    "part",
                    "add",
                    "box",
                    "--name",
                    "Podium",
                    "-P",
                    "length=52",
                    "-P",
                    "width=88",
                    "-P",
                    "height=10",
                ],
                "wait_preview": True,
            },
        {
                "id": "lower-mass",
                "label": "Add lower tower mass",
                "argv": [
                    "-p",
                    "{project_path}",
                    "part",
                    "add",
                    "box",
                    "--name",
                    "LowerMass",
                    "-P",
                    "length=36",
                    "-P",
                    "width=64",
                    "-P",
                    "height=20",
                    "-pos",
                    "0,0,10",
                ],
                "wait_preview": True,
            },
        {
                "id": "mid-mass",
                "label": "Add mid setback mass",
                "argv": [
                    "-p",
                    "{project_path}",
                    "part",
                    "add",
                    "box",
                    "--name",
                    "MidMass",
                    "-P",
                    "length=28",
                    "-P",
                    "width=44",
                    "-P",
                    "height=22",
                    "-pos",
                    "0,0,30",
                ],
                "wait_preview": True,
            },
        {
                "id": "upper-shaft",
                "label": "Add upper shaft",
                "argv": [
                    "-p",
                    "{project_path}",
                    "part",
                    "add",
                    "box",
                    "--name",
                    "UpperShaft",
                    "-P",
                    "length=20",
                    "-P",
                    "width=28",
                    "-P",
                    "height=24",
                    "-pos",
                    "0,0,52",
                ],
                "wait_preview": True,
            },
    ]
