# ruff: noqa: F403, F405, E501
from .freecad_live_preview_demo_base import *  # noqa: F403


def __curiosity_steps_lg0_1():
    return [
        {
            "id": "left-rocker",
            "label": "Add left rocker beam",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "LeftRocker",
                "-P",
                "length=46",
                "-P",
                "width=3.5",
                "-P",
                "height=3",
                "-pos",
                "-8,-22,22",
            ],
            "wait_preview": True,
        },
        {
            "id": "right-rocker",
            "label": "Add right rocker beam",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "RightRocker",
                "-P",
                "length=46",
                "-P",
                "width=3.5",
                "-P",
                "height=3",
                "-pos",
                "-8,18.5,22",
            ],
            "wait_preview": True,
        },
        {
            "id": "left-bogie",
            "label": "Add left bogie beam",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "LeftBogie",
                "-P",
                "length=34",
                "-P",
                "width=3",
                "-P",
                "height=3",
                "-pos",
                "-20,-22,18",
            ],
            "wait_preview": True,
        },
        {
            "id": "right-bogie",
            "label": "Add right bogie beam",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "RightBogie",
                "-P",
                "length=34",
                "-P",
                "width=3",
                "-P",
                "height=3",
                "-pos",
                "-20,19,18",
            ],
            "wait_preview": True,
        },
        {
            "id": "left-front-link",
            "label": "Add left front suspension link",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "LeftFrontLink",
                "-P",
                "length=18",
                "-P",
                "width=3",
                "-P",
                "height=3",
                "-pos",
                "18,-22,19",
                "-rot",
                "0,0,-28",
            ],
            "wait_preview": True,
        },
    ]
