# ruff: noqa: F403, F405, E501
from .freecad_live_preview_demo_base import *  # noqa: F403


def _mod_cg2_1():
    return [
        {
                "id": "left-crown-pier",
                "label": "Add left crown pier",
                "argv": [
                    "-p",
                    "{project_path}",
                    "part",
                    "add",
                    "box",
                    "--name",
                    "LeftCrownPier",
                    "-P",
                    "length=16",
                    "-P",
                    "width=10",
                    "-P",
                    "height=26",
                    "-pos",
                    "-12,0,76",
                ],
                "wait_preview": True,
            },
        {
                "id": "right-crown-pier",
                "label": "Add right crown pier",
                "argv": [
                    "-p",
                    "{project_path}",
                    "part",
                    "add",
                    "box",
                    "--name",
                    "RightCrownPier",
                    "-P",
                    "length=16",
                    "-P",
                    "width=10",
                    "-P",
                    "height=26",
                    "-pos",
                    "12,0,76",
                ],
                "wait_preview": True,
            },
        {
                "id": "central-crown",
                "label": "Add central crown tower",
                "argv": [
                    "-p",
                    "{project_path}",
                    "part",
                    "add",
                    "box",
                    "--name",
                    "CentralCrown",
                    "-P",
                    "length=16",
                    "-P",
                    "width=16",
                    "-P",
                    "height=32",
                    "-pos",
                    "0,0,76",
                ],
                "wait_preview": True,
            },
        {
                "id": "upper-crown",
                "label": "Add upper crown",
                "argv": [
                    "-p",
                    "{project_path}",
                    "part",
                    "add",
                    "box",
                    "--name",
                    "UpperCrown",
                    "-P",
                    "length=10",
                    "-P",
                    "width=12",
                    "-P",
                    "height=18",
                    "-pos",
                    "0,0,108",
                ],
                "wait_preview": True,
            },
        {
                "id": "mast-lower",
                "label": "Add mast base",
                "argv": [
                    "-p",
                    "{project_path}",
                    "part",
                    "add",
                    "cylinder",
                    "--name",
                    "MastLower",
                    "-P",
                    "radius=2.2",
                    "-P",
                    "height=14",
                    "-pos",
                    "0,0,126",
                ],
                "wait_preview": True,
            },
    ]
