# ruff: noqa: F403, F405, E501
from .freecad_live_preview_demo_base import *  # noqa: F403


def __curiosity_steps_lg0_2():
    return [
        {
            "id": "right-front-link",
            "label": "Add right front suspension link",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "RightFrontLink",
                "-P",
                "length=18",
                "-P",
                "width=3",
                "-P",
                "height=3",
                "-pos",
                "18,19,19",
                "-rot",
                "0,0,28",
            ],
            "wait_preview": True,
        },
        {
            "id": "left-rear-link",
            "label": "Add left rear suspension link",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "LeftRearLink",
                "-P",
                "length=16",
                "-P",
                "width=3",
                "-P",
                "height=3",
                "-pos",
                "-33,-22,18",
                "-rot",
                "0,0,30",
            ],
            "wait_preview": True,
        },
        {
            "id": "right-rear-link",
            "label": "Add right rear suspension link",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "RightRearLink",
                "-P",
                "length=16",
                "-P",
                "width=3",
                "-P",
                "height=3",
                "-pos",
                "-33,19,18",
                "-rot",
                "0,0,-30",
            ],
            "wait_preview": True,
        },
        {
            "id": "left-front-wheel",
            "label": "Add left front wheel",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "cylinder",
                "--name",
                "LeftFrontWheel",
                "-P",
                "radius=12",
                "-P",
                "height=6",
                "-pos",
                "24,-25,12",
                "-rot",
                "90,0,0",
            ],
            "wait_preview": True,
        },
        {
            "id": "left-mid-wheel",
            "label": "Add left middle wheel",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "cylinder",
                "--name",
                "LeftMidWheel",
                "-P",
                "radius=12",
                "-P",
                "height=6",
                "-pos",
                "-2,-25,10",
                "-rot",
                "90,0,0",
            ],
            "wait_preview": True,
        },
    ]
