# ruff: noqa: F403, F405, E501
from .freecad_live_preview_demo_base import *  # noqa: F403


def __curiosity_steps_lg0_7():
    return [
        {
            "id": "align-right-front-axle-block",
            "label": "Attach right front axle block",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "21",
                "15",
                "--x",
                "center",
                "--to-x",
                "center",
                "--y",
                "max",
                "--to-y",
                "min",
                "--z",
                "max",
                "--to-z",
                "max",
                "--dz",
                "1.0",
            ],
            "wait_preview": True,
        },
        {
            "id": "right-mid-axle-block",
            "label": "Add right middle axle block",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "RightMidAxleBlock",
                "-P",
                "length=6",
                "-P",
                "width=8",
                "-P",
                "height=8",
                "-pos",
                "-5,17,14",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-right-mid-axle-block",
            "label": "Attach right middle axle block",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "22",
                "16",
                "--x",
                "center",
                "--to-x",
                "center",
                "--y",
                "max",
                "--to-y",
                "min",
                "--z",
                "max",
                "--to-z",
                "max",
                "--dz",
                "3.0",
            ],
            "wait_preview": True,
        },
        {
            "id": "right-rear-axle-block",
            "label": "Add right rear axle block",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "RightRearAxleBlock",
                "-P",
                "length=6",
                "-P",
                "width=8",
                "-P",
                "height=8",
                "-pos",
                "-29,17,16",
            ],
            "wait_preview": True,
        },
    ]
