# ruff: noqa: F403, F405, E501
from .freecad_live_preview_demo_base import *  # noqa: F403


def __curiosity_steps_lg0_6():
    return [
        {
            "id": "left-mid-axle-block",
            "label": "Add left middle axle block",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "LeftMidAxleBlock",
                "-P",
                "length=6",
                "-P",
                "width=8",
                "-P",
                "height=8",
                "-pos",
                "-5,-24,14",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-left-mid-axle-block",
            "label": "Attach left middle axle block",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "19",
                "13",
                "--x",
                "center",
                "--to-x",
                "center",
                "--y",
                "min",
                "--to-y",
                "max",
                "--z",
                "max",
                "--to-z",
                "max",
                "--dz",
                "3.0",
            ],
            "wait_preview": True,
        },
        {
            "id": "left-rear-axle-block",
            "label": "Add left rear axle block",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "LeftRearAxleBlock",
                "-P",
                "length=6",
                "-P",
                "width=8",
                "-P",
                "height=8",
                "-pos",
                "-29,-24,16",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-left-rear-axle-block",
            "label": "Attach left rear axle block",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "20",
                "14",
                "--x",
                "center",
                "--to-x",
                "center",
                "--y",
                "min",
                "--to-y",
                "max",
                "--z",
                "max",
                "--to-z",
                "max",
                "--dz",
                "1.0",
            ],
            "wait_preview": True,
        },
        {
            "id": "right-front-axle-block",
            "label": "Add right front axle block",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "RightFrontAxleBlock",
                "-P",
                "length=6",
                "-P",
                "width=8",
                "-P",
                "height=8",
                "-pos",
                "21,17,16",
            ],
            "wait_preview": True,
        },
    ]
