# ruff: noqa: F403, F405, E501
from .freecad_live_preview_demo_base import *  # noqa: F403


def __curiosity_steps_lg0_4():
    return [
        {
            "id": "align-right-mid-wheel-outboard",
            "label": "Push right middle wheel to mirrored track width",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "16",
                "0",
                "--y",
                "min",
                "--to-y",
                "max",
                "--dy",
                "8.0",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-right-rear-wheel-outboard",
            "label": "Push right rear wheel to mirrored track width",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "17",
                "0",
                "--y",
                "min",
                "--to-y",
                "max",
                "--dy",
                "8.0",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-left-rocker-wheel-plane",
            "label": "Seat left rocker into wheel plane",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "4",
                "12",
                "--y",
                "min",
                "--to-y",
                "max",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-right-rocker-wheel-plane",
            "label": "Seat right rocker into wheel plane",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "5",
                "15",
                "--y",
                "max",
                "--to-y",
                "min",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-left-bogie-wheel-plane",
            "label": "Seat left bogie into wheel plane",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "6",
                "13",
                "--y",
                "min",
                "--to-y",
                "max",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-right-bogie-wheel-plane",
            "label": "Seat right bogie into wheel plane",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "7",
                "16",
                "--y",
                "max",
                "--to-y",
                "min",
            ],
            "wait_preview": True,
        },
    ]
