# ruff: noqa: F403, F405, E501
from .freecad_live_preview_demo_base import *  # noqa: F403


def __curiosity_steps_lg0_14():
    return [
        {
            "id": "align-mast-column",
            "label": "Attach mast column to pedestal",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "29",
                "28",
                "--x",
                "center",
                "--to-x",
                "center",
                "--y",
                "center",
                "--to-y",
                "center",
                "--z",
                "min",
                "--to-z",
                "max",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-camera-bridge",
            "label": "Attach camera bridge to mast",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "30",
                "29",
                "--x",
                "center",
                "--to-x",
                "center",
                "--dx",
                "-1.0",
                "--y",
                "center",
                "--to-y",
                "center",
                "--z",
                "min",
                "--to-z",
                "max",
                "--dz",
                "-3.0",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-camera-pods",
            "label": "Hang camera pods under bridge",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "31",
                "30",
                "--x",
                "center",
                "--to-x",
                "min",
                "--dx",
                "2.0",
                "--z",
                "max",
                "--to-z",
                "min",
                "--dz",
                "1.0",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-right-camera-pod",
            "label": "Hang right camera pod under bridge",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "33",
                "30",
                "--x",
                "center",
                "--to-x",
                "max",
                "--dx",
                "-2.0",
                "--z",
                "max",
                "--to-z",
                "min",
                "--dz",
                "1.0",
            ],
            "wait_preview": True,
        },
    ]
