# ruff: noqa: F403, F405, E501
from .freecad_live_preview_demo_base import *  # noqa: F403


def __mars_rover_steps_lg0_2():
    return [
        {
            "id": "right-rear-wheel",
            "label": "Mirror right rear wheel",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "mirror",
                "7",
                "--plane",
                "XZ",
                "--name",
                "RightRearWheel",
            ],
            "wait_preview": True,
        },
        {
            "id": "right-rocker",
            "label": "Mirror right suspension beam",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "mirror",
                "4",
                "--plane",
                "XZ",
                "--name",
                "RightRocker",
            ],
            "wait_preview": True,
        },
        {
            "id": "mast-base",
            "label": "Add mast base",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "cylinder",
                "--name",
                "MastBase",
                "-P",
                "radius=3.6",
                "-P",
                "height=12",
                "-pos",
                "8,0,37",
            ],
            "wait_preview": True,
        },
        {
            "id": "mast-neck",
            "label": "Add camera mast",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "cylinder",
                "--name",
                "MastNeck",
                "-P",
                "radius=1.7",
                "-P",
                "height=26",
                "-pos",
                "8,0,49",
            ],
            "wait_preview": True,
        },
        {
            "id": "camera-head",
            "label": "Add camera head",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "CameraHead",
                "-P",
                "length=16",
                "-P",
                "width=8",
                "-P",
                "height=7",
                "-pos",
                "0,-4,74",
            ],
            "wait_preview": True,
        },
        {
            "id": "sensor-bar",
            "label": "Add sensor bar",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "SensorBar",
                "-P",
                "length=24",
                "-P",
                "width=4",
                "-P",
                "height=3",
                "-pos",
                "-4,-2,81",
            ],
            "wait_preview": True,
        },
    ]
