# ruff: noqa: F403, F405, E501
from .freecad_live_preview_demo_base import *  # noqa: F403


def __curiosity_steps_lg0_16():
    return [
        {
            "id": "align-hga-stem",
            "label": "Attach antenna stem",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "37",
                "1",
                "--x",
                "center",
                "--to-x",
                "center",
                "--dx",
                "10.0",
                "--y",
                "center",
                "--to-y",
                "center",
                "--dy",
                "11.0",
                "--z",
                "min",
                "--to-z",
                "max",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-hga-dish",
            "label": "Attach antenna dish",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "38",
                "37",
                "--x",
                "center",
                "--to-x",
                "center",
                "--y",
                "center",
                "--to-y",
                "center",
                "--dy",
                "3.0",
                "--z",
                "min",
                "--to-z",
                "max",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-arm-shoulder",
            "label": "Attach arm shoulder to front bay",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "39",
                "2",
                "--x",
                "min",
                "--to-x",
                "max",
                "--dx",
                "-1.0",
                "--y",
                "center",
                "--to-y",
                "center",
                "--z",
                "center",
                "--to-z",
                "center",
                "--dz",
                "-3.0",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-arm-upper",
            "label": "Attach upper arm",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "40",
                "39",
                "--x",
                "min",
                "--to-x",
                "max",
                "--dx",
                "-1.5",
                "--y",
                "center",
                "--to-y",
                "center",
                "--z",
                "center",
                "--to-z",
                "center",
                "--dz",
                "-1.5",
            ],
            "wait_preview": True,
        },
    ]
