# ruff: noqa: F403, F405, E501
from .freecad_live_preview_demo_base import *  # noqa: F403


def __mars_rover_steps_lg0_1():
    return [
        {
            "id": "left-rocker",
            "label": "Add left suspension beam",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "LeftRocker",
                "-P",
                "length=72",
                "-P",
                "width=4",
                "-P",
                "height=3",
                "-pos",
                "-36,-17,20",
            ],
            "wait_preview": True,
        },
        {
            "id": "left-front-wheel",
            "label": "Add left front wheel",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "cylinder",
                "--name",
                "LeftFrontWheel",
                "-P",
                "radius=12",
                "-P",
                "height=6",
                "-pos",
                "24,-20,12",
                "-rot",
                "90,0,0",
            ],
            "wait_preview": True,
        },
        {
            "id": "left-mid-wheel",
            "label": "Add left middle wheel",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "cylinder",
                "--name",
                "LeftMidWheel",
                "-P",
                "radius=13",
                "-P",
                "height=6",
                "-pos",
                "0,-20,12",
                "-rot",
                "90,0,0",
            ],
            "wait_preview": True,
        },
        {
            "id": "left-rear-wheel",
            "label": "Add left rear wheel",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "cylinder",
                "--name",
                "LeftRearWheel",
                "-P",
                "radius=12",
                "-P",
                "height=6",
                "-pos",
                "-26,-20,12",
                "-rot",
                "90,0,0",
            ],
            "wait_preview": True,
        },
        {
            "id": "right-front-wheel",
            "label": "Mirror right front wheel",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "mirror",
                "5",
                "--plane",
                "XZ",
                "--name",
                "RightFrontWheel",
            ],
            "wait_preview": True,
        },
        {
            "id": "right-mid-wheel",
            "label": "Mirror right middle wheel",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "mirror",
                "6",
                "--plane",
                "XZ",
                "--name",
                "RightMidWheel",
            ],
            "wait_preview": True,
        },
    ]
