# ruff: noqa: F403, F405, E501
from .freecad_live_preview_demo_base import *  # noqa: F403


def __curiosity_steps_lg0_15():
    return [
        {
            "id": "align-chemcam",
            "label": "Attach ChemCam barrel",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "32",
                "30",
                "--x",
                "center",
                "--to-x",
                "center",
                "--y",
                "center",
                "--to-y",
                "center",
                "--z",
                "center",
                "--to-z",
                "center",
                "--dz",
                "-2.0",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-rtg-body",
            "label": "Attach RTG body to rear bridge",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "34",
                "3",
                "--x",
                "max",
                "--to-x",
                "min",
                "--dx",
                "-2.0",
                "--y",
                "center",
                "--to-y",
                "center",
                "--dy",
                "9.0",
                "--z",
                "center",
                "--to-z",
                "center",
                "--dz",
                "2.0",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-rtg-cap",
            "label": "Cap the RTG body",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "35",
                "34",
                "--x",
                "max",
                "--to-x",
                "min",
                "--dx",
                "0.5",
                "--y",
                "center",
                "--to-y",
                "center",
                "--z",
                "center",
                "--to-z",
                "center",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-rtg-strut",
            "label": "Support the RTG",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "36",
                "34",
                "--x",
                "max",
                "--to-x",
                "max",
                "--dx",
                "8.0",
                "--y",
                "center",
                "--to-y",
                "center",
                "--z",
                "center",
                "--to-z",
                "center",
                "--dz",
                "-3.0",
            ],
            "wait_preview": True,
        },
    ]
