# ruff: noqa: F403, F405, E501
from .freecad_live_preview_demo_base import *  # noqa: F403


def __curiosity_steps_lg0_0():
    return [
        {
            "id": "create-project",
            "label": "Create FreeCAD project",
            "argv": ["document", "new", "--name", "Curiosity", "-o", "{project_path}"],
            "wait_preview": False,
        },
        {
            "id": "start-live-preview",
            "label": "Start poll-mode live preview",
            "argv": [
                "-p",
                "{project_path}",
                "preview",
                "live",
                "start",
                "--recipe",
                "quick",
                "--mode",
                "poll",
                "--source-poll-ms",
                "500",
                "--poll-ms",
                "700",
                "--root-dir",
                "{live_root}",
            ],
            "wait_preview": True,
            "manual_session_payload": True,
        },
        {
            "id": "lower-chassis",
            "label": "Add lower chassis tub",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "LowerChassis",
                "-P",
                "length=50",
                "-P",
                "width=34",
                "-P",
                "height=8",
                "-pos",
                "-10,-17,25",
            ],
            "wait_preview": True,
        },
        {
            "id": "upper-deck",
            "label": "Add upper instrument deck",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "UpperDeck",
                "-P",
                "length=34",
                "-P",
                "width=28",
                "-P",
                "height=8",
                "-pos",
                "-8,-14,33",
            ],
            "wait_preview": True,
        },
        {
            "id": "front-avionics",
            "label": "Add front avionics bay",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "FrontAvionics",
                "-P",
                "length=14",
                "-P",
                "width=26",
                "-P",
                "height=8",
                "-pos",
                "24,-13,31",
            ],
            "wait_preview": True,
        },
        {
            "id": "rear-bridge",
            "label": "Add rear bridge deck",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "RearBridge",
                "-P",
                "length=14",
                "-P",
                "width=22",
                "-P",
                "height=5",
                "-pos",
                "-24,-11,33",
            ],
            "wait_preview": True,
        },
    ]
