# ruff: noqa: F403, F405, E501
from .freecad_live_preview_demo_base import *  # noqa: F403


def __curiosity_steps_lg0_5():
    return [
        {
            "id": "align-left-front-link-wheel-plane",
            "label": "Seat left front link into wheel plane",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "8",
                "12",
                "--y",
                "min",
                "--to-y",
                "max",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-right-front-link-wheel-plane",
            "label": "Seat right front link into wheel plane",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "9",
                "15",
                "--y",
                "max",
                "--to-y",
                "min",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-left-rear-link-wheel-plane",
            "label": "Seat left rear link into wheel plane",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "10",
                "14",
                "--y",
                "min",
                "--to-y",
                "max",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-right-rear-link-wheel-plane",
            "label": "Seat right rear link into wheel plane",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "11",
                "17",
                "--y",
                "max",
                "--to-y",
                "min",
            ],
            "wait_preview": True,
        },
        {
            "id": "left-front-axle-block",
            "label": "Add left front axle block",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "LeftFrontAxleBlock",
                "-P",
                "length=6",
                "-P",
                "width=8",
                "-P",
                "height=8",
                "-pos",
                "21,-24,16",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-left-front-axle-block",
            "label": "Attach left front axle block",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "18",
                "12",
                "--x",
                "center",
                "--to-x",
                "center",
                "--y",
                "min",
                "--to-y",
                "max",
                "--z",
                "max",
                "--to-z",
                "max",
                "--dz",
                "1.0",
            ],
            "wait_preview": True,
        },
    ]
