# ruff: noqa: F403, F405, E501
from .freecad_live_preview_demo_base import *  # noqa: F403


def __curiosity_steps_lg0_12():
    return [
        {
            "id": "hga-stem",
            "label": "Add high-gain antenna stem",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "cylinder",
                "--name",
                "HGAStem",
                "-P",
                "radius=1.2",
                "-P",
                "height=14",
                "-pos",
                "-1,11,43",
            ],
            "wait_preview": True,
        },
        {
            "id": "hga-dish",
            "label": "Add high-gain antenna dish",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "cylinder",
                "--name",
                "HGADish",
                "-P",
                "radius=6.3",
                "-P",
                "height=1.3",
                "-pos",
                "1,14,56",
                "-rot",
                "0,90,0",
            ],
            "wait_preview": True,
        },
        {
            "id": "arm-shoulder",
            "label": "Add robotic arm shoulder",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "cylinder",
                "--name",
                "ArmShoulder",
                "-P",
                "radius=2.4",
                "-P",
                "height=8",
                "-pos",
                "32,0,30",
                "-rot",
                "0,90,0",
            ],
            "wait_preview": True,
        },
        {
            "id": "arm-upper",
            "label": "Add robotic arm upper segment",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "cylinder",
                "--name",
                "ArmUpper",
                "-P",
                "radius=1.6",
                "-P",
                "height=16",
                "-pos",
                "35,0,28",
                "-rot",
                "0,90,-26",
            ],
            "wait_preview": True,
        },
        {
            "id": "arm-fore",
            "label": "Add robotic forearm",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "cylinder",
                "--name",
                "ArmFore",
                "-P",
                "radius=1.4",
                "-P",
                "height=15",
                "-pos",
                "46,0,19",
                "-rot",
                "0,90,18",
            ],
            "wait_preview": True,
        },
    ]
