# ruff: noqa: F403, F405, E501
from .freecad_live_preview_demo_base import *  # noqa: F403


def __curiosity_steps_lg0_10():
    return [
        {
            "id": "align-right-bogie-pivot-housing",
            "label": "Seat right bogie pivot housing",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "27",
                "7",
                "--x",
                "center",
                "--to-x",
                "center",
                "--y",
                "max",
                "--to-y",
                "max",
                "--z",
                "max",
                "--to-z",
                "max",
                "--dz",
                "5.0",
            ],
            "wait_preview": True,
        },
        {
            "id": "mast-pedestal",
            "label": "Add mast pedestal",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "cylinder",
                "--name",
                "MastPedestal",
                "-P",
                "radius=3.8",
                "-P",
                "height=10",
                "-pos",
                "2,0,41",
            ],
            "wait_preview": True,
        },
        {
            "id": "mast-column",
            "label": "Add mast column",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "cylinder",
                "--name",
                "MastColumn",
                "-P",
                "radius=1.7",
                "-P",
                "height=28",
                "-pos",
                "2,0,51",
            ],
            "wait_preview": True,
        },
        {
            "id": "camera-bar",
            "label": "Add mast camera bridge",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "CameraBridge",
                "-P",
                "length=18",
                "-P",
                "width=4",
                "-P",
                "height=3",
                "-pos",
                "-5,-2,79",
            ],
            "wait_preview": True,
        },
        {
            "id": "camera-pods",
            "label": "Add stereo camera pods",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "LeftCameraPod",
                "-P",
                "length=7",
                "-P",
                "width=6",
                "-P",
                "height=7",
                "-pos",
                "-11,-7,73",
            ],
            "wait_preview": True,
        },
    ]
