# ruff: noqa: F403, F405, E501
from .freecad_live_preview_demo_base import *  # noqa: F403


def __curiosity_steps_lg0_13():
    return [
        {
            "id": "turret",
            "label": "Add drill turret",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "sphere",
                "--name",
                "ToolTurret",
                "-P",
                "radius=4.1",
                "-pos",
                "56,0,13",
            ],
            "wait_preview": True,
        },
        {
            "id": "deck-sensor-pack",
            "label": "Add deck sensor pack",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "DeckSensorPack",
                "-P",
                "length=12",
                "-P",
                "width=7",
                "-P",
                "height=4",
                "-pos",
                "-10,-3,41",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-upper-deck",
            "label": "Seat upper deck on chassis",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "1",
                "0",
                "--y",
                "center",
                "--to-y",
                "center",
                "--z",
                "min",
                "--to-z",
                "max",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-front-avionics",
            "label": "Seat front avionics",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "2",
                "1",
                "--x",
                "min",
                "--to-x",
                "max",
                "--y",
                "center",
                "--to-y",
                "center",
                "--z",
                "min",
                "--to-z",
                "min",
                "--dz",
                "-2",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-rear-bridge",
            "label": "Seat rear bridge",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "3",
                "1",
                "--x",
                "max",
                "--to-x",
                "min",
                "--dx",
                "-1.5",
                "--y",
                "center",
                "--to-y",
                "center",
                "--z",
                "min",
                "--to-z",
                "min",
            ],
            "wait_preview": True,
        },
    ]
