# ruff: noqa: F403, F405, E501
from .freecad_live_preview_demo_base import *  # noqa: F403


def __curiosity_steps_lg0_3():
    return [
        {
            "id": "left-rear-wheel",
            "label": "Add left rear wheel",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "cylinder",
                "--name",
                "LeftRearWheel",
                "-P",
                "radius=12",
                "-P",
                "height=6",
                "-pos",
                "-26,-25,12",
                "-rot",
                "90,0,0",
            ],
            "wait_preview": True,
        },
        {
            "id": "right-front-wheel",
            "label": "Add right front wheel",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "cylinder",
                "--name",
                "RightFrontWheel",
                "-P",
                "radius=12",
                "-P",
                "height=6",
                "-pos",
                "24,19,12",
                "-rot",
                "90,0,0",
            ],
            "wait_preview": True,
        },
        {
            "id": "right-mid-wheel",
            "label": "Add right middle wheel",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "cylinder",
                "--name",
                "RightMidWheel",
                "-P",
                "radius=12",
                "-P",
                "height=6",
                "-pos",
                "-2,19,10",
                "-rot",
                "90,0,0",
            ],
            "wait_preview": True,
        },
        {
            "id": "right-rear-wheel",
            "label": "Add right rear wheel",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "cylinder",
                "--name",
                "RightRearWheel",
                "-P",
                "radius=12",
                "-P",
                "height=6",
                "-pos",
                "-26,19,12",
                "-rot",
                "90,0,0",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-right-front-wheel-outboard",
            "label": "Push right front wheel to mirrored track width",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "15",
                "0",
                "--y",
                "min",
                "--to-y",
                "max",
                "--dy",
                "8.0",
            ],
            "wait_preview": True,
        },
    ]
