# ruff: noqa: F403, F405, E501
from .freecad_live_preview_demo_base import *  # noqa: F403


def __curiosity_steps_lg0_11():
    return [
        {
            "id": "chemcam-barrel",
            "label": "Add ChemCam barrel",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "cylinder",
                "--name",
                "ChemCamBarrel",
                "-P",
                "radius=0.9",
                "-P",
                "height=9",
                "-pos",
                "-2,-0.5,75",
                "-rot",
                "0,90,0",
            ],
            "wait_preview": True,
        },
        {
            "id": "right-camera-pod",
            "label": "Add right camera pod",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "RightCameraPod",
                "-P",
                "length=7",
                "-P",
                "width=6",
                "-P",
                "height=7",
                "-pos",
                "4,1,73",
            ],
            "wait_preview": True,
        },
        {
            "id": "rtg-body",
            "label": "Add rear RTG body",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "cylinder",
                "--name",
                "RTGBody",
                "-P",
                "radius=6.5",
                "-P",
                "height=18",
                "-pos",
                "-28,13,35",
                "-rot",
                "90,0,0",
            ],
            "wait_preview": True,
        },
        {
            "id": "rtg-cap",
            "label": "Add RTG cap",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "cone",
                "--name",
                "RTGCap",
                "-P",
                "radius1=6.2",
                "-P",
                "radius2=2.8",
                "-P",
                "height=6",
                "-pos",
                "-32,13,35",
                "-rot",
                "90,0,0",
            ],
            "wait_preview": True,
        },
        {
            "id": "rtg-strut",
            "label": "Add RTG support strut",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "RTGStrut",
                "-P",
                "length=11",
                "-P",
                "width=3",
                "-P",
                "height=3",
                "-pos",
                "-20,11,35",
                "-rot",
                "0,0,-18",
            ],
            "wait_preview": True,
        },
    ]
