# ruff: noqa: F403, F405, E501
from .freecad_live_preview_demo_base import *  # noqa: F403


def _mod_cg4_0():
    return [
        {
                "id": "create-project",
                "label": "Create FreeCAD project",
                "argv": ["document", "new", "--name", "OrbitalRelay", "-o", "{project_path}"],
                "wait_preview": False,
            },
        {
                "id": "start-live-preview",
                "label": "Start poll-mode live preview",
                "argv": [
                    "-p",
                    "{project_path}",
                    "preview",
                    "live",
                    "start",
                    "--recipe",
                    "quick",
                    "--mode",
                    "poll",
                    "--source-poll-ms",
                    "500",
                    "--poll-ms",
                    "700",
                    "--root-dir",
                    "{live_root}",
                ],
                "wait_preview": True,
                "manual_session_payload": True,
            },
        {
                "id": "base-deck",
                "label": "Add base deck",
                "argv": [
                    "-p",
                    "{project_path}",
                    "part",
                    "add",
                    "box",
                    "--name",
                    "BaseDeck",
                    "-P",
                    "length=60",
                    "-P",
                    "width=40",
                    "-P",
                    "height=8",
                ],
                "wait_preview": True,
            },
        {
                "id": "core-spine",
                "label": "Add core spine",
                "argv": [
                    "-p",
                    "{project_path}",
                    "part",
                    "add",
                    "cylinder",
                    "--name",
                    "CoreSpine",
                    "-P",
                    "radius=9",
                    "-P",
                    "height=24",
                    "-pos",
                    "0,0,8",
                ],
                "wait_preview": True,
            },
        {
                "id": "tail-fin",
                "label": "Add tail fin",
                "argv": [
                    "-p",
                    "{project_path}",
                    "part",
                    "add",
                    "box",
                    "--name",
                    "TailFin",
                    "-P",
                    "length=10",
                    "-P",
                    "width=6",
                    "-P",
                    "height=24",
                    "-pos",
                    "0,-18,8",
                ],
                "wait_preview": True,
            },
        {
                "id": "sensor-dome",
                "label": "Add sensor dome",
                "argv": [
                    "-p",
                    "{project_path}",
                    "part",
                    "add",
                    "sphere",
                    "--name",
                    "SensorDome",
                    "-P",
                    "radius=12",
                    "-pos",
                    "0,0,34",
                ],
                "wait_preview": True,
            },
    ]
