# ruff: noqa: F403, F405, E501
from .freecad_live_preview_demo_base import *  # noqa: F403


def __mars_rover_steps_lg0_0():
    return [
        {
            "id": "create-project",
            "label": "Create FreeCAD project",
            "argv": ["document", "new", "--name", "MarsRover", "-o", "{project_path}"],
            "wait_preview": False,
        },
        {
            "id": "start-live-preview",
            "label": "Start poll-mode live preview",
            "argv": [
                "-p",
                "{project_path}",
                "preview",
                "live",
                "start",
                "--recipe",
                "quick",
                "--mode",
                "poll",
                "--source-poll-ms",
                "500",
                "--poll-ms",
                "700",
                "--root-dir",
                "{live_root}",
            ],
            "wait_preview": True,
            "manual_session_payload": True,
        },
        {
            "id": "chassis-belly",
            "label": "Add chassis belly",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "ChassisBelly",
                "-P",
                "length=72",
                "-P",
                "width=28",
                "-P",
                "height=6",
                "-pos",
                "-36,-14,24",
            ],
            "wait_preview": True,
        },
        {
            "id": "deck-module",
            "label": "Add upper deck module",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "DeckModule",
                "-P",
                "length=46",
                "-P",
                "width=24",
                "-P",
                "height=7",
                "-pos",
                "-14,-12,30",
            ],
            "wait_preview": True,
        },
        {
            "id": "rear-power-pack",
            "label": "Add rear power pack",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "RearPowerPack",
                "-P",
                "length=24",
                "-P",
                "width=22",
                "-P",
                "height=14",
                "-pos",
                "-34,-11,37",
            ],
            "wait_preview": True,
        },
        {
            "id": "front-bumper",
            "label": "Add front bumper",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "FrontBumper",
                "-P",
                "length=12",
                "-P",
                "width=24",
                "-P",
                "height=3",
                "-pos",
                "28,-12,25",
            ],
            "wait_preview": True,
        },
    ]
