# ruff: noqa: F403, F405, E501
from .freecad_live_preview_demo_base import *  # noqa: F403


def __curiosity_steps_lg0_9():
    return [
        {
            "id": "align-right-rocker-pivot-housing",
            "label": "Seat right rocker pivot housing",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "25",
                "5",
                "--x",
                "center",
                "--to-x",
                "center",
                "--y",
                "max",
                "--to-y",
                "max",
                "--z",
                "max",
                "--to-z",
                "max",
                "--dz",
                "3.0",
            ],
            "wait_preview": True,
        },
        {
            "id": "left-bogie-pivot-housing",
            "label": "Add left bogie pivot housing",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "LeftBogiePivotHousing",
                "-P",
                "length=8",
                "-P",
                "width=8",
                "-P",
                "height=6",
                "-pos",
                "-7,-22,17",
            ],
            "wait_preview": True,
        },
        {
            "id": "align-left-bogie-pivot-housing",
            "label": "Seat left bogie pivot housing",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "align",
                "26",
                "6",
                "--x",
                "center",
                "--to-x",
                "center",
                "--y",
                "min",
                "--to-y",
                "min",
                "--z",
                "max",
                "--to-z",
                "max",
                "--dz",
                "5.0",
            ],
            "wait_preview": True,
        },
        {
            "id": "right-bogie-pivot-housing",
            "label": "Add right bogie pivot housing",
            "argv": [
                "-p",
                "{project_path}",
                "part",
                "add",
                "box",
                "--name",
                "RightBogiePivotHousing",
                "-P",
                "length=8",
                "-P",
                "width=8",
                "-P",
                "height=6",
                "-pos",
                "-7,17,17",
            ],
            "wait_preview": True,
        },
    ]
