# ruff: noqa: F403, F405, E501
"""End-to-end tests using a real video generated by ffmpeg.

Covers save/load roundtrip, media probing, real-world editing workflows,
CLI subprocess, and melt rendering.
"""
import os
import sys
import json
import shutil
import tempfile
import subprocess
import re
import time
import pytest
from PIL import Image, ImageStat
from cli_anything.shotcut.core.session import Session
from cli_anything.shotcut.core import project as proj_mod
from cli_anything.shotcut.core import timeline as tl_mod
from cli_anything.shotcut.core import filters as filt_mod
from cli_anything.shotcut.core import media as media_mod
from cli_anything.shotcut.core import export as export_mod
from cli_anything.shotcut.core import transitions as trans_mod
from cli_anything.shotcut.core import preview as preview_mod
from cli_anything.shotcut.utils.time import (
    timecode_to_frames, frames_to_timecode, parse_time_input,
    frames_to_seconds, seconds_to_frames, format_duration,
)
from cli_anything.shotcut.utils.mlt_xml import (
    get_property, get_all_producers, create_producer,
)


VIDEO = "/root/shotcut/1.mp4"


PNG_MAGIC = b"\x89PNG\r\n\x1a\n"


# fmt: off
__all__ = ['Image', 'ImageStat', 'PNG_MAGIC', 'Session', 'VIDEO', 'create_producer', 'export_mod', 'filt_mod', 'format_duration', 'frames_to_seconds', 'frames_to_timecode', 'get_all_producers', 'get_property', 'json', 'media_mod', 'os', 'parse_time_input', 'preview_mod', 'proj_mod', 'pytest', 're', 'seconds_to_frames', 'shutil', 'subprocess', 'sys', 'tempfile', 'time', 'timecode_to_frames', 'tl_mod', 'trans_mod']  # noqa: E501
# fmt: on
