# ruff: noqa: F403, F405, E501
from .test_full_e2e_helpers import *  # noqa: F403


class TestWriterToPDF:
    """True E2E: Writer document -> ODF -> PDF via LibreOffice headless."""

    def test_simple_writer_to_pdf(self, tmp_dir):
        proj = create_document(doc_type="writer", name="PDF Test")
        add_heading(proj, text="Hello World", level=1)
        add_paragraph(
            proj,
            text="This paragraph was generated by cli-anything-libreoffice "
            "and converted to PDF by LibreOffice headless.",
        )

        pdf_path = os.path.join(tmp_dir, "simple.pdf")
        result = export(proj, pdf_path, preset="pdf", overwrite=True)

        assert os.path.exists(result["output"]), f"PDF not created: {result['output']}"
        assert result["format"] == "pdf"
        assert result["file_size"] > 0
        # PDF magic bytes
        with open(result["output"], "rb") as f:
            magic = f.read(5)
        assert magic == b"%PDF-", f"Not a valid PDF file (magic: {magic!r})"
        print(f"\n  PDF output: {result['output']} ({result['file_size']:,} bytes)")

    def test_rich_writer_to_pdf(self, tmp_dir):
        """Full Writer document with headings, tables, lists -> PDF."""
        proj = create_document(doc_type="writer", name="Full Report")
        add_heading(proj, text="Quarterly Report", level=1)
        add_paragraph(proj, text="Executive summary of Q1 performance.")
        add_heading(proj, text="Sales Data", level=2)
        add_table(
            proj,
            rows=3,
            cols=3,
            data=[
                ["Product", "Q1 Sales", "Q2 Sales"],
                ["Widget A", "$15,000", "$18,000"],
                ["Widget B", "$12,000", "$14,500"],
            ],
        )
        add_list(
            proj,
            items=[
                "Increase marketing spend by 20%",
                "Launch Widget C in Q3",
                "Expand to EU market",
            ],
        )
        add_page_break(proj)
        add_heading(proj, text="Conclusion", level=1)
        add_paragraph(proj, text="Results exceeded expectations.")

        pdf_path = os.path.join(tmp_dir, "full_report.pdf")
        result = export(proj, pdf_path, preset="pdf", overwrite=True)

        assert os.path.exists(result["output"])
        assert result["file_size"] > 1000, "PDF suspiciously small for a rich document"
        with open(result["output"], "rb") as f:
            assert f.read(5) == b"%PDF-"
        print(f"\n  Rich PDF: {result['output']} ({result['file_size']:,} bytes)")

    def test_styled_writer_to_pdf(self, tmp_dir):
        """Writer with custom styles -> PDF."""
        proj = create_document(doc_type="writer")
        create_style(
            proj,
            "BoldTitle",
            properties={"font_size": "24pt", "bold": True, "color": "#003366"},
        )
        add_paragraph(proj, text="Styled Document Title")
        apply_style(proj, "BoldTitle", 0)
        add_paragraph(proj, text="Normal body text following the styled title.")

        pdf_path = os.path.join(tmp_dir, "styled.pdf")
        result = export(proj, pdf_path, preset="pdf", overwrite=True)
        assert os.path.exists(result["output"])
        assert result["file_size"] > 0
        print(f"\n  Styled PDF: {result['output']} ({result['file_size']:,} bytes)")


class TestWriterToDOCX:
    """True E2E: Writer document -> ODF -> DOCX via LibreOffice headless."""

    def test_writer_to_docx(self, tmp_dir):
        proj = create_document(doc_type="writer", name="DOCX Test")
        add_heading(proj, text="Word Document", level=1)
        add_paragraph(proj, text="Converted from ODF to DOCX via LibreOffice.")
        add_table(proj, rows=2, cols=2, data=[["A", "B"], ["C", "D"]])

        docx_path = os.path.join(tmp_dir, "output.docx")
        result = export(proj, docx_path, preset="docx", overwrite=True)

        assert os.path.exists(result["output"])
        assert result["format"] == "docx"
        # DOCX is a ZIP file (OOXML)
        assert zipfile.is_zipfile(result["output"]), (
            "DOCX is not a valid ZIP/OOXML file"
        )
        with zipfile.ZipFile(result["output"]) as zf:
            names = zf.namelist()
            assert "[Content_Types].xml" in names, "Missing OOXML content types"
            assert any("document.xml" in n for n in names), (
                "Missing document.xml in DOCX"
            )
        print(f"\n  DOCX output: {result['output']} ({result['file_size']:,} bytes)")
